<?php

function cgy_str_mk(...$args) {return \Cgy\util\Str::mk(...$args); }
function cgy_str_each(...$args) {return \Cgy\util\Str::each(...$args); }
function cgy_str_split(...$args) {return \Cgy\util\Str::split(...$args); }
function cgy_str_replace(...$args) {return \Cgy\util\Str::replace(...$args); }
function cgy_str_replaceAll(...$args) {return \Cgy\util\Str::replaceAll(...$args); }
function cgy_str_camel(...$args) {return \Cgy\util\Str::camel(...$args); }
function cgy_str_snake(...$args) {return \Cgy\util\Str::snake(...$args); }
function cgy_str_has(...$args) {return \Cgy\util\Str::has(...$args); }
function cgy_str_hasAny(...$args) {return \Cgy\util\Str::hasAny(...$args); }
function cgy_str_hasAll(...$args) {return \Cgy\util\Str::hasAll(...$args); }
function cgy_str_begin(...$args) {return \Cgy\util\Str::begin(...$args); }
function cgy_str_beginUp(...$args) {return \Cgy\util\Str::beginUp(...$args); }
function cgy_str_end(...$args) {return \Cgy\util\Str::end(...$args); }
function cgy_str_tpl(...$args) {return \Cgy\util\Str::tpl(...$args); }
function cgy_str_tplkey(...$args) {return \Cgy\util\Str::tplkey(...$args); }
function cgy_str_nonce(...$args) {return \Cgy\util\Str::nonce(...$args); }
function cgy_is_any(...$args) {return \Cgy\util\Is::any(...$args); }
function cgy_is_all(...$args) {return \Cgy\util\Is::all(...$args); }
function cgy_is_indexed(...$args) {return \Cgy\util\Is::indexed(...$args); }
function cgy_is_associate(...$args) {return \Cgy\util\Is::associate(...$args); }
function cgy_is_onedimension(...$args) {return \Cgy\util\Is::onedimension(...$args); }
function cgy_is_nemarr(...$args) {return \Cgy\util\Is::nemarr(...$args); }
function cgy_is_nemstr(...$args) {return \Cgy\util\Is::nemstr(...$args); }
function cgy_is_lower(...$args) {return \Cgy\util\Is::lower(...$args); }
function cgy_is_upper(...$args) {return \Cgy\util\Is::upper(...$args); }
function cgy_is_lower_upper(...$args) {return \Cgy\util\Is::lower_upper(...$args); }
function cgy_is_query(...$args) {return \Cgy\util\Is::query(...$args); }
function cgy_is_ntf(...$args) {return \Cgy\util\Is::ntf(...$args); }
function cgy_is_explodable(...$args) {return \Cgy\util\Is::explodable(...$args); }
function cgy_is_json(...$args) {return \Cgy\util\Is::json(...$args); }
function cgy_is_xml(...$args) {return \Cgy\util\Is::xml(...$args); }
function cgy_is_remote(...$args) {return \Cgy\util\Is::remote(...$args); }
function cgy_is_nem(...$args) {return \Cgy\util\Is::nem(...$args); }
function cgy_is_set(...$args) {return \Cgy\util\Is::set(...$args); }
function cgy_is_def(...$args) {return \Cgy\util\Is::def(...$args); }
function cgy_arr_mk(...$args) {return \Cgy\util\Arr::mk(...$args); }
function cgy_arr_copy(...$args) {return \Cgy\util\Arr::copy(...$args); }
function cgy_arr_last(...$args) {return \Cgy\util\Arr::last(...$args); }
function cgy_arr_find(...$args) {return \Cgy\util\Arr::find(...$args); }
function cgy_arr_len(...$args) {return \Cgy\util\Arr::len(...$args); }
function cgy_arr_key(...$args) {return \Cgy\util\Arr::key(...$args); }
function cgy_arr_dimension(...$args) {return \Cgy\util\Arr::dimension(...$args); }
function cgy_arr_equal(...$args) {return \Cgy\util\Arr::equal(...$args); }
function cgy_arr_extend(...$args) {return \Cgy\util\Arr::extend(...$args); }
function cgy_arr_indexed(...$args) {return \Cgy\util\Arr::indexed(...$args); }
function cgy_arr_uni(...$args) {return \Cgy\util\Arr::uni(...$args); }
function cgy_arr_sortVersion(...$args) {return \Cgy\util\Arr::sortVersion(...$args); }
function cgy_path_root(...$args) {return \Cgy\util\Path::root(...$args); }
function cgy_path_cnst(...$args) {return \Cgy\util\Path::cnst(...$args); }
function cgy_path_mk(...$args) {return \Cgy\util\Path::mk(...$args); }
function cgy_path_relative(...$args) {return \Cgy\util\Path::relative(...$args); }
function cgy_path_find(...$args) {return \Cgy\util\Path::find(...$args); }
function cgy_path_exists(...$args) {return \Cgy\util\Path::exists(...$args); }
function cgy_path_traverse(...$args) {return \Cgy\util\Path::traverse(...$args); }
function cgy_path_mkdir(...$args) {return \Cgy\util\Path::mkdir(...$args); }
function cgy_path_fix(...$args) {return \Cgy\util\Path::fix(...$args); }
function cgy_path_up(...$args) {return \Cgy\util\Path::up(...$args); }
function cgy_path_del(...$args) {return \Cgy\util\Path::del(...$args); }
function cgy_cls_find(...$args) {return \Cgy\util\Cls::find(...$args); }
function cgy_cls_pre(...$args) {return \Cgy\util\Cls::pre(...$args); }
function cgy_cls_name(...$args) {return \Cgy\util\Cls::name(...$args); }
function cgy_cls_ref(...$args) {return \Cgy\util\Cls::ref(...$args); }
function cgy_cls_filter(...$args) {return \Cgy\util\Cls::filter(...$args); }
function cgy_cls_methods(...$args) {return \Cgy\util\Cls::methods(...$args); }
function cgy_cls_methodNames(...$args) {return \Cgy\util\Cls::methodNames(...$args); }
function cgy_cls_hasMethod(...$args) {return \Cgy\util\Cls::hasMethod(...$args); }
function cgy_cls_properties(...$args) {return \Cgy\util\Cls::properties(...$args); }
function cgy_cls_propertyNames(...$args) {return \Cgy\util\Cls::propertyNames(...$args); }
function cgy_cls_hasProperty(...$args) {return \Cgy\util\Cls::hasProperty(...$args); }
function cgy_conv_a2j(...$args) {return \Cgy\util\Conv::a2j(...$args); }
function cgy_conv_j2a(...$args) {return \Cgy\util\Conv::j2a(...$args); }
function cgy_conv_a2u(...$args) {return \Cgy\util\Conv::a2u(...$args); }
function cgy_conv_u2a(...$args) {return \Cgy\util\Conv::u2a(...$args); }
function cgy_conv_a2x(...$args) {return \Cgy\util\Conv::a2x(...$args); }
function cgy_conv_x2a(...$args) {return \Cgy\util\Conv::x2a(...$args); }
function cgy_conv_a2p(...$args) {return \Cgy\util\Conv::a2p(...$args); }
function cgy_conv_sizeToStr(...$args) {return \Cgy\util\Conv::sizeToStr(...$args); }
function cgy_num_round(...$args) {return \Cgy\util\Num::round(...$args); }
function cgy_num_fl(...$args) {return \Cgy\util\Num::fl(...$args); }
function cgy_num_it(...$args) {return \Cgy\util\Num::it(...$args); }
function cgy_num_rd(...$args) {return \Cgy\util\Num::rd(...$args); }
function cgy_num_kg(...$args) {return \Cgy\util\Num::kg(...$args); }
function cgy_num_kg_always(...$args) {return \Cgy\util\Num::kg_always(...$args); }
function cgy_num_file_size(...$args) {return \Cgy\util\Num::file_size(...$args); }
function cgy_session_set(...$args) {return \Cgy\util\Session::set(...$args); }
function cgy_session_get(...$args) {return \Cgy\util\Session::get(...$args); }
function cgy_session_del(...$args) {return \Cgy\util\Session::del(...$args); }
function cgy_session_has(...$args) {return \Cgy\util\Session::has(...$args); }
function cgy_server_get(...$args) {return \Cgy\util\Server::get(...$args); }
function cgy_server_has(...$args) {return \Cgy\util\Server::has(...$args); }
function cgy_server_pre(...$args) {return \Cgy\util\Server::pre(...$args); }
function cgy_server_key(...$args) {return \Cgy\util\Server::key(...$args); }
function cgy_secure_fix(...$args) {return \Cgy\util\Secure::fix(...$args); }
function cgy_secure_str(...$args) {return \Cgy\util\Secure::str(...$args); }
